version: '2'

services:

  dachs:
    image: chbrandt/dachs:server
    tty: true
    ports:
      - '80:80'
    volumes:
      - ./inputs:/var/gavo/inputs
    networks:
      - appnet
    depends_on:
      - 'postgres'
    links:
      - 'postgres'

  postgres:
    image: chbrandt/dachs:postgres
    tty: true
    networks:
      - appnet

networks:
  appnet:
    driver: 'bridge'

volumes:
  data:
    driver: 'local'
