version: '3'

services:

  dachs:
      container_name: dachs
      image: dachs:${INSTALL_REPO:-latest}
      build:
        context: ./dachs
        args:
          INSTALL_REPO: "${INSTALL_REPO}"   # Builds 'stable' if not defined.
      tty: true
      network_mode: 'bridge'
      ports:
        - 8080:8080
      volumes:
        - "${DACHS_LOGS_PATH:-./logs/dachs}:/var/gavo/logs"

  awstats:
      container_name: awstats
      image: dachs:awstats
      depends_on:
        - dachs
      build:
        context: ./awstats
      tty: true
      network_mode: 'bridge'
      ports:
        - 80:80
      volumes:
        - "${DACHS_LOGS_PATH:-./logs/dachs}:/var/gavo/logs:ro"
