version: '3'

services:

  postgres:
      container_name: dachs_postgres
      image: dachs:postgres
      build:
          context: ./postgres
      tty: true
      network_mode: 'bridge'
      ports:
        - 5432:5432

  dachs:
      container_name: dachs_server
      image: "dachs:${INSTALL_REPO:-latest}"
      command: ["--rcfile", "serve.sh"]
      depends_on:
        - dachs_postgres
      build:
        context: ./dachs
        args:
          INSTALL_REPO: "${INSTALL_REPO}"
      tty: true
      network_mode: 'bridge'
      ports:
        - 8080:8080
      volumes:
        - "${DACHS_LOGS_PATH:-./logs/dachs}:/var/gavo/logs"

  awstats:
      container_name: dachs_awstats
      image: dachs:awstats
      depends_on:
        - dachs_server
      build:
        context: ./awstats
      tty: true
      network_mode: 'bridge'
      ports:
        - 80:80
      volumes:
        - "${DACHS_LOGS_PATH:-./logs/dachs}:/var/gavo/logs:ro"
