version: '3'

services:

  dachs:
      container_name: dachs
      image: dachs:latest
      command: ['--rcfile','/start.sh']
      # build:
      #   context: ./dachs
      #   args:
      #     INSTALL_REPO: "${INSTALL_REPO}"   # Builds 'latest'/ "gavo" if NOT defined.
      tty: true
      network_mode: 'bridge'
      ports:
        - 8080:8080
      volumes:
        - "${DACHS_LOGS_PATH:-./tmp/logs}:/var/gavo/logs"
