version: '3'
services:
    dachs:
        container_name: dachs
        build:
            context: ./dachs
        image: dachs
        tty: true
        network_mode: 'bridge'
        ports:
            - '8080:8080'
        volumes:
          - ./logs/dachs:/var/gavo/logs
    awstats:
        container_name: awstats
        build:
            context: ./awstats
        image: awstats
        tty: true
        network_mode: 'bridge'
        ports:
            - '80:80'
        depends_on:
            - dachs
        volumes:
          - ./logs/dachs:/var/gavo/logs:ro
